### ISSUE TITLE
error with patch

### ISSUE THREAD

**Issue by jackygoule** [juliogonzalez/sc3u-linux#1]
hello after i run install games with successful, i clone this repository .
but when i want to run ./sc3u-patcher.sh
ERROR: Required binary cat not found. Install it to proceed
I have the same message with sudo linux32 ./sc3u-patcher.sh 
Thanks for your job

**Comment by juliogonzalez** [comment]
As the error says, it seems `cat` is not available in your system.

For openSUSE Leap 15.3, it is part of `coreutils`

```
$ which cat
/usr/bin/cat
$ rpm -qf /usr/bin/cat
coreutils-8.32-3.2.1.x86_64
```
Try to find the package that provides `cat` for your distribution, and install it.

**Comment by juliogonzalez** [comment]
I should probably state at the README what programs are required to use `sc3u-patcher.sh`, but for now:

- curl
- cat
- patch
- tar

If any of those is missing, you need to install the package that provides it.

**Comment by juliogonzalez** [comment]
@jackygoule was the problem fixed by installing the package that provides `cat`?
