### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by ProfStrongman** [juliogonzalez/sc3u-linux#2]
ERROR: Required binary curl not found. Install it to proceed

I get the above error.  Curl is installed.  Ubuntu 20.04.4 LTS

**Comment by juliogonzalez** [comment]
What's the output of `which curl`?

If the official `curl` from the Ubuntu repositories is installed, it should be:
```
root@a5e58fb8719b:/# which curl
/usr/bin/curl
```
If `which curl` returns nothing, provide the output of `echo $PATH` (it could be `/usr/bin` is not in there, for whatever reason).

**Comment by juliogonzalez** [comment]
Any news @ProfStrongman?

**Comment by juliogonzalez** [comment]
Feel free to reopen if the problem still exists after the official `curl` package is installed.
